#+TITLE: Company setup
#+AUTHOR: Steve Lane
#+DESCRIPTION: A description of my current company setup.
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+PROPERTY: header-args :tangle yes

* Introduction

This file provides details on my current =company= setup. It is intended as a literate programming approach to structure my =company= setup.

If you want to use some (all) of this setup, you'll need to change directories appropriately. You can tangle this file to Emacs lisp using =C-c C-v C-t=, which will create *company-setup.el* in the same folder as this file. You can then source this in your *init.el* file. Or, use the following in your *init.el*

#+BEGIN_SRC emacs-lisp :exports none :tangle no
  (org-babel-load-file "~/.emacs.d/company-setup.org")
#+END_SRC

I've got a couple of different setups here. To use a particular setup, make sure it has =:tangle yes= in the header arguments.

* Basic setup

I had this basic setup, but hadn't enabled =company-mode= globally. What's happening here is that we set up some values for delays etc for when completions get popped up. We also limit tips to 10.

We define keys as well so that we get TAB completion.

#+BEGIN_SRC emacs-lisp :exports none :tangle yes
  (use-package company
    :ensure t
    :config
    ;; (setq ess-use-company 'script-only)
    (setq company-selection-wrap-around t
	  company-tooltip-align-annotations t
	  company-idle-delay 0.36
	  company-minimum-prefix-length 2
	  company-tooltip-limit 10)
    ;; TABS for completion
    (define-key company-active-map [return] nil)
    (define-key company-active-map [tab] 'company-complete-common)
    (define-key company-active-map (kbd "TAB") 'company-complete-common)
    (define-key company-active-map (kbd "M-TAB") 'company-complete-selection)
    ;; Enable it globally
    (add-hook 'after-init-hook 'global-company-mode)
    )
#+END_SRC
