#+TITLE: Company setup
#+AUTHOR: Steve Lane
#+DESCRIPTION: A description of my current company setup.
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+PROPERTY: header-args :tangle yes

* Introduction

This file provides details on my current =company= setup. It is intended as a literate programming approach to structure my =company= setup.

If you want to use some (all) of this setup, you'll need to change directories appropriately. You can tangle this file to Emacs lisp using =C-c C-v C-t=, which will create *company-setup.el* in the same folder as this file. You can then source this in your *init.el* file. Or, use the following in your *init.el*

#+BEGIN_SRC emacs-lisp :exports none :tangle no
  (org-babel-load-file "~/.emacs.d/company-setup.org")
#+END_SRC

I've got a couple of different setups here. To use a particular setup, make sure it has =:tangle yes= in the header arguments.

* Basic setup

The following modeline uses the spacemacs modeline, [[https://github.com/TheBB/spaceline][spaceline]]. Because I'm on a mac, the colours get stuffed up, so the =powerline-image-apple-rgb= setting fixes that (found [[https://emacs.stackexchange.com/questions/14984/emacs-powerline-inconsistent-colors-behind-arrows][here]]):

#+BEGIN_SRC emacs-lisp :exports none :tangle yes
  (use-package spaceline
    :ensure t
    :init
    ;; (setq powerline-default-separator 'utf-8)
    ;; (setq powerline-image-apple-rgb t)
    :config
    ;; (require 'spaceline-config)
    ;; (spaceline-emacs-theme)
    )

#+END_SRC

The separator uses =utf-8=, you can check what others are available, e.g. =C-h v powerline-default-separator=.

** Bling it up

Using =all-the-icons= we can bling things up a bit:

#+BEGIN_SRC emacs-lisp :exports none :tangle yes
  (use-package all-the-icons
    :ensure t
    :defer t
    )

  (use-package spaceline-all-the-icons
    :ensure t
    :config
    (spaceline-all-the-icons-theme)
    (spaceline-all-the-icons--setup-neotree)
    (setq spaceline-all-the-icons-hide-long-buffer-path t)
    (setq spaceline-all-the-icons-slim-render t)
    )
#+END_SRC

Here, the theme is set, and some options to make things a little slimmer.

* moody/minions

The following setup is taken directly from [[https://github.com/tarsius/moody][moody github]] and [[https://github.com/tarsius/minions][tarsius github]]. No configuration at the moment.

#+BEGIN_SRC emacs-lisp :exports none :tangle no
  (use-package moody
    :ensure t
    :config
    (setq x-underline-at-descent-line t)
    (moody-replace-mode-line-buffer-identification)
    (moody-replace-vc-mode)
    )

  (use-package minions
    :ensure t
    :pin melpa-stable
    :config (minions-mode 1)
    )
#+END_SRC
