#+TITLE: Org-roam setup
#+AUTHOR: Steve Lane
#+DESCRIPTION: A description of my current org-roam setup. This is a literate file which can be tangled to the source required to mimic my org-roam setup.
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+PROPERTY: header-args :tangle yes

* Introduction

  I've now migrated over to v2 of [[https://github.com/org-roam/org-roam/tree/v2][Org-roam]]. To do this, I needed to follow a number of steps.

  1. Make sure that ~gcc~ is in my path ([[https://org-roam.discourse.group/t/v2-do-we-want-org-roam-project-to-host-an-executable-file/1549/5][follow the thread here]]).
  2. Add new spacemacs leader keys and capture templates (below).

* Capture templates

Similar to [[file:org-setup.org][my org setup]], we'd like some specific org-roam capture templates. For example, I'm going to have common tags, such as person, division, process, code. I'd like to have those pre-populated wherever possible. The following will create such capture templates.

** Template definitions

   #+header: :tangle yes
   #+begin_src emacs-lisp :export yes
     (setq
      ;; Define custom org-roam capture templates
      org-roam-capture-templates
      '(
        ("p" "Permanent Note" plain "%?"
         :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n\n[[id:7b759d89-71fb-4066-8cd8-def55a7a7dec][Weekly Review]]")
         :unnarrowed t
         )
        ("i" "Ideas and Somedays" plain "%?"
         :if-new (file+head "ideas/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
         :unnarrowed t
         )
        ("l" "Literature Note" plain "%?"
         :if-new (file+head "literature/%<%Y%m%d%H%M%S>-${citar-citekey}.org" "#+title: ${note-title}. ${citar-citekey} (${citar-date}).\n#+created: %U\n\n")
         :unnarrowed t
         )
        ("m" "Meeting Note" plain "%?"
         :if-new (file+head "meetings/%<%Y%m%d%H%M%S>-${slug}.org" "
     ,#+ROAM_TAGS: %^G
     ,#+title: ${title}

     Date: %^{Meeting date}u
     Time-stamp: <>

     Attendees:

     ,* Notes Prior

     ,* Notes During

     ")
         :unnarrowed t
         )
        )
      org-roam-dailies-capture-templates
      '(
        ("d" "Daily (throughout) notes" entry "* %<%H:%M>\n  * %?" :target (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))
        ("j" "Journalling" plain "%^{What went well today?}
     %^{What didn't go as well? Can I do anything to address them?}
     %^{Should I focus on something in particular tomorrow?}
     %^{Are there any patterns I'm beginning to notice?}
     %^{How did I feel today?}
     \n%?
     "
         :target (file+head "journal/%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n#+filetags: :JOURNAL:\n")
         :unnarrowed t
         )
        )
      )
   #+end_src

* Searching through your notes

  To make it a little easier to search, use ripgrep.

  #+begin_src emacs-lisp :tangle yes :export yes
    (defun sprazza/org-roam-search ()
      "Search in the org-roam directory with `rg'."
      (interactive)
      (spacemacs/compleseus-search nil (expand-file-name org-roam-directory)))

    (progn
      (spacemacs/set-leader-keys
        "aors" 'sprazza/org-roam-search
        "aordc" 'org-roam-dailies-capture-today
        )

      (spacemacs/set-leader-keys-for-major-mode 'org-mode
        "rs" 'sprazza/org-roam-search
        )
      )
  #+end_src

* Helper Functions

  These helpers come/are adapted from [[https://github.com/org-roam/org-roam/wiki/User-contributed-Tricks#showing-the-number-of-backlinks-for-each-node-in-org-roam-node-find][this link]].

  #+begin_src emacs-lisp :tangle yes :export yes
    ;; Make sure only to do these after org-roam is loaded
    (with-eval-after-load 'org-roam
      (cl-defmethod org-roam-node-directories ((node org-roam-node))
        (if-let ((dirs (file-name-directory (file-relative-name (org-roam-node-file node) org-roam-directory))))
            (format "(%s)" (car (split-string dirs "/")))
          ""))

      (cl-defmethod org-roam-node-backlinkscount ((node org-roam-node))
        (let* ((count (caar (org-roam-db-query
                             [:select (funcall count source)
                                      :from links
                                      :where (= dest $s1)
                                      :and (= type "id")]
                             (org-roam-node-id node)))))
          (format "[%d]" count)))

      (cl-defmethod org-roam-node-date ((node org-roam-node))
        (format-time-string "%Y-%m-%d" (org-roam-node-file-mtime node))
        )

    ;; (setq org-roam-node-display-template "${directories:10} ${tags:20} ${title:100} ${backlinkscount:6}")
      (setq
       org-roam-node-display-template "${title:*} ${directories:20} ${tags:40} ${backlinkscount:6} ${date:10}"
       org-roam-db-autosync-mode t
       )
    )
  #+end_src

* Prompting

  I'm once again trying to get my PKM working better, so I'm trying out some extra prompting. The following presents the prompts in their own buffer when performing the reviews.

  #+begin_src emacs-lisp :tangle yes
    (defun sprazza/daily-review-prompts()
      "Opens a buffer that contains review prompts."
      (interactive)
      (switch-to-buffer "*Daily Review*")
      (erase-buffer)
      (org-mode)

      (insert
       "* Daily Review\n"
       "** What surprised me?\n"
       "** What decision/s were made?\n"
       "** What did I learn?\n"
       "** What should become a permanent note?\n"
        )
      )

    (defun sprazza/daily-review-from-agenda ()
      "Allows daily review to proceed directly from the agenda."
      (interactive)

      ;; Start clean
      (delete-other-windows)

      ;; Set up variable names
      (let ((left-window (selected-window))
            right-window top-right bottom-right)

        ;; Split for left/right
        (setq right-window (split-window-right))

        ;; Split right side into top/bottom
        (select-window right-window)
        (setq bottom-right (split-window-below))
        (setq top-right (selected-window))

        ;; Top right: prompts
        (select-window top-right)
        (sprazza/daily-review-prompts)

        ;; Bottom right: meetings agenda
        (select-window bottom-right)
        (org-agenda nil "m")

        ;; Left: yesterday's org-roam daily
        (select-window left-window)
        (org-roam-dailies-goto-yesterday 1 "d")
        )

      )

    (with-eval-after-load 'org-agenda
      (define-key org-agenda-mode-map (kbd "R")
                  #'sprazza/daily-review-from-agenda))
  #+end_src

  This next session now turns to the weekly review. In this review, I want to surface all permanent notes I've made and then create the connections back to other permanent notes if required.

  #+begin_src emacs-lisp :tangle yes
    (defun sprazza/weekly-review-prompts()
      "Opens a buffer that contains review prompts."
      (interactive)
      (switch-to-buffer "*Weekly Review*")
      (erase-buffer)
      (org-mode)

      (insert
       "* Weekly Review\n"
       "** What idea keeps recurring?\n"
       "** What changed my behaviour?\n"
       "** What pattern am I noticing?\n"
       "** What can be stated as a general principle?\n"
       "** What synthesis note should exist?\n"
        )
      )

    (defun sprazza/weekly-review-from-agenda ()
      "Allows weekly review to proceed directly from the agenda."
      (interactive)

      ;; Start clean
      (delete-other-windows)

      ;; Then pretty easily run through the opening commands...
      (org-roam-buffer-display-dedicated
       (org-roam-node-from-id "7b759d89-71fb-4066-8cd8-def55a7a7dec")
       )
      (sprazza/weekly-review-prompts)

      )

    (with-eval-after-load 'org-agenda
      (define-key org-agenda-mode-map (kbd "W")
                  #'sprazza/weekly-review-from-agenda))
  #+end_src
